version: '3.4'

services:
  templateproduct.templateservice:
    image: templateservice
    build:
      context: .
      dockerfile: src/services/TemplateService/TemplateProduct.TemplateService/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"